// f it we tank
// no code in this project was generated by LLMs or AI


// TODO:
// cursor trail and visuals
// bottom scoreboard
// maybe a home screen i guess.
// make helper functions for font rendering for custom spacing? it might be expensive to render letter by letter
// modular level design system
// THEN move into core gameplay, moving, shooting, mining
// then i say improve the visual quality of the level and the gameplay elements

// global vars
let app;

let gameState;
let frameCount = 0
let cframeRate = 0;
let avgTime = 0;
let lastTime = performance.now();

let bgContainer;
let missionContainer;
let cursorSprite;
let fpsText;

let tankBGTexture;
let missionBannerTexture
let cursorTexture

async function init() {
    // i hope pixi is as easy as p5 lmao
    app = new PIXI.Application();
    await app.init({
        width: 854,
        height: 480,
        backgroundColor: 0xff0000 // red, shouldnt be seen.
    })
}

document.querySelector('main').appendChild(app.canvas);

await loadAssets();

gameState = "missionbrief"; // initial launch state, will be changed.

setupScene(); // guess what this function does!

app.ticker.add(gameLoop);

async function loadAssets(){ // akin to preload() in p5
    tankBGTexture = await PIXI.Assets.load('assets/images/tank_background_billboard_white.png')
    missionBannerTexture = await PIXI.Assets.load('assets/images/mission_info.png')
    cursorTexture = await PIXI.Assets.load('assets/images/cursor_1.png')

    // fonts are weirder
    await PIXI.Assets.load({
        alias: "weFont",
        src: 'assets/en_US.ttf'
    });

}

function setupMissionBrief() { // combine the tank bg and mission brief into one container.
    // only separete containers if you need diff update logic, diff z ordering, or if parts are reused.
    bgContainer = new PIXI.Container();
    app.stage.addChild(bgContainer);
  
  // initialize
  gameState = "missionbrief"
  bgBuffer = createGraphics(width+64,height+64)
  bgBuffer.tint("#E7E6B3");
  for(let i = 0; i < floor(width/64) + 2; i++){
    for(let j = 0; j < floor(height/64) + 2; j++){
      bgBuffer.image(tankBG, i * 64, j * 64);
    }
  }
}

function draw() {
    background("red"); // should never be seen.
    switch (gameState) {
        case "missionbrief":
            image(bgBuffer, frameCount%64-64, -frameCount%64)
            push()
            tint("#C04736");
            for(let i = 0; i < 5; i++){
                image(missionBanner, 0, (height/5)+i*47, width, 67)
            }
            pop()// pop tint
            noStroke()
            fill("#CCA82A")
            rect(0,(height/5)+height/60,width,(height/40))
            rect(0,(67*5)-height/60,width,(height/40))
            
            // 3 words.
            fill("#973627")
            textAlign(CENTER,CENTER)
            textSize(52)
            text("Mission 1", width/2+(height/60), (height/5)+(height/8)+height/60)
            stroke("#634921")
            strokeWeight(8)
            fill("#FAE59F")
            text("Mission 1", width/2, (height/5)+(height/8))

            noStroke()
            fill("#973627")
            textAlign(CENTER,CENTER)
            textSize(32)
            text("Enemy Tanks: 1", width/2+(height/60), (height/5)+(height/3)+height/60)
            stroke("#634921")
            strokeWeight(8)
            fill("#FAE59F")
            text("Enemy Tanks: 1", width/2, (height/5)+(height/3))

            break;

    }

    // render cursor (is it always on?)
    push()
    tint('#096EE7')
    image(cursor, mouseX-15, mouseY-15, 30, 30)
    pop()



    // frameRate
    if (frameCount % 10 == 0){
        cframeRate = floor( (10 / avgTime) * 1000)
        avgTime = 0
    } else {
        avgTime += deltaTime;
    }
    noStroke();
    fill("green")
    textSize(12)
    text(cframeRate, 12,12);


}